source 'https://github.com/CocoaPods/Specs.git'

target 'NADocumentPicker_Example' do
  use_frameworks!

  pod 'BrightFutures'
  pod 'NADocumentPicker', :path => '../'

  target 'NADocumentPicker_Tests' do
    inherit! :search_paths
  end
end
