source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NADocumentPicker_Example', :exclusive => true do
  pod 'NADocumentPicker', :path => '../'
end

target 'NADocumentPicker_Tests', :exclusive => true do
  pod 'NADocumentPicker', :path => '../'
end
