source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NADocumentPicker_Example' do
  inherit! :search_paths
  pod 'NADocumentPicker', :path => '../'
end

target 'NADocumentPicker_Tests' do
  inherit! :search_paths
  pod 'BrightFutures'
end
